name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        exclude:
          - os: 'windows-latest'
            python: '3.8'

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: pip install -r test_requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: make coverage
      - name: Run codecov
        uses: codecov/codecov-action@v1
